CREATE TABLE IF NOT EXISTS member
(id SERIAL NOT NULL PRIMARY KEY,
nickname VARCHAR(50) NOT NULL,
passcache VARCHAR(129) NOT NULL,
wins SMALLINT,
defeat SMALLINT,
draw SMALLINT,
elo SMALLINT NOT NULL,
max_elo SMALLINT NOT NULL);

CREATE TABLE IF NOT EXISTS session
(id SERIAL NOT NULL PRIMARY KEY,
user_id INTEGER NOT NULL,
session_id VARCHAR(129) NOT NULL,
created INTEGER NOT NULL,
ended INTEGER NOT NULL);

CREATE TABLE IF NOT EXISTS match
(matchID SERIAL NOT NULL PRIMARY KEY,
result SMALLINT NOT NULL,
first_player_id INTEGER NOT NULL,
second_player_id INTEGER NOT NULL,
first_player_elo SMALLINT NOT NULL,
second_player_elo SMALLINT NOT NULL,
first_elo_change SMALLINT,
second_elo_change SMALLINT,
commentary TEXT);

CREATE TABLE IF NOT EXISTS invite 
(id SERIAL NOT NULL PRIMARY KEY,
invite_id VARCHAR(129) NOT NULL);